// <auto-generated />
using System;
using CreatioAutoPackageLinkerBlazor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreatioAutoPackageLinkerBlazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230425144146_RemoveColumnRecordIdInPackageType")]
    partial class RemoveColumnRecordIdInPackageType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBeRoot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorInfo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsModule")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRootPackage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Maintainer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageUId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rang")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Successfully")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.PackageForType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecordUId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.ToTable("PackageForTypes");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.ProductForType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.ToTable("ProductForTypes");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductForTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.HasIndex("ProductForTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.TypeOfPackageForProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProductId");

                    b.ToTable("TypeOfPackageForProducts");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.Object.PackageHierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasePackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DependOnPackageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsModified")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecordInactive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_Id");

                    b.HasIndex("BasePackageId");

                    b.HasIndex("DependOnPackageId");

                    b.ToTable("PackageHierarchies");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Package", b =>
                {
                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.Project", "Project")
                        .WithMany("Package")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Project", b =>
                {
                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.ProductForType", "ProductForType")
                        .WithMany("Projects")
                        .HasForeignKey("ProductForTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductForType");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.TypeOfPackageForProduct", b =>
                {
                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.PackageForType", "Package")
                        .WithMany("TypeOfPackageForProducts")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.ProductForType", "Product")
                        .WithMany("TypeOfPackageForProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.Object.PackageHierarchy", b =>
                {
                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.Package", "BasePackage")
                        .WithMany("PackageHierarchyDependOnPackages")
                        .HasForeignKey("BasePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreatioAutoPackageLinkerBlazor.Data.DbClass.Package", "DependOnPackage")
                        .WithMany("PackageHierarchyBasePackages")
                        .HasForeignKey("DependOnPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasePackage");

                    b.Navigation("DependOnPackage");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Package", b =>
                {
                    b.Navigation("PackageHierarchyBasePackages");

                    b.Navigation("PackageHierarchyDependOnPackages");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.PackageForType", b =>
                {
                    b.Navigation("TypeOfPackageForProducts");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.ProductForType", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("TypeOfPackageForProducts");
                });

            modelBuilder.Entity("CreatioAutoPackageLinkerBlazor.Data.DbClass.Project", b =>
                {
                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
